# Generated by Django 5.0.2 on 2024-12-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='first_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
